In [3]:
import pandas as pd
from pathlib import Path

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()  # sube un nivel
FILES_PATH = PROJECT_ROOT / "persistence" / "files"
STAGING_PATH = FILES_PATH / "STAGING"

In [22]:
parquet_path = Path(STAGING_PATH / "SBSA" / "name_2.0_1644.parquet")

In [23]:
df = pd.read_parquet(parquet_path)

In [24]:
df.head()

,msg_no,offset,msg_len,mti,enc,bitmap_hex,body_hex,parse_ok,function_code,function_role,de24_raw_hex,block
0,31627,21899743,74,1644,EBCDIC_DIGITS,80000100000100000200000000000000,f6f9f7f0f4f0f0f1f0f5f0f2f5f0f0f1f2f6f0f1f1f3f0...,True,697,HEADER,f6f9f7,2.0
1,31628,21899821,298,1644,EBCDIC_DIGITS,80000100000140000200000c10000000,f6f4f0f2f3f7f0f1f6f4f2f3f0f0f0f3f6f1f3f9f2f7f0...,True,640,None,f6f4f0,2.0
2,31629,21900123,298,1644,EBCDIC_DIGITS,80000100000140000200000c10000000,f6f4f0f2f3f7f0f1f6f4f2f3f0f0f6f0f9f1f0f0f0f0f0...,True,640,None,f6f4f0,2.0
3,31630,21900425,298,1644,EBCDIC_DIGITS,80000100000140000200000c10000000,f6f4f0f2f3f7f0f1f6f4f2f3f0f1f2f4f9f1f3f8f9f3f0...,True,640,None,f6f4f0,2.0
4,31631,21900727,298,1644,EBCDIC_DIGITS,80000100000140000200000c10000000,f6f4f0f2f3f7f0f1f6f4f2f3f0f1f8f8f7f4f9f7f8f2f5...,True,640,None,f6f4f0,2.0

In [25]:
df.tail()

,msg_no,offset,msg_len,mti,enc,bitmap_hex,body_hex,parse_ok,function_code,function_role,de24_raw_hex,block
2247,41052,27848534,472,1644,EBCDIC_DIGITS,800001800001c0000200000810000000,f6f8f5f6f8f6f1f4f1f2f0f1f4f8f0f0f4f9f7f8f2f0f1...,True,685,None,f6f8f5,2.0
2248,41053,27849010,472,1644,EBCDIC_DIGITS,800001800001c0000200000810000000,f6f8f5f6f8f6f1f4f1f2f0f1f4f8f0f0f4f9f7f8f2f0f1...,True,685,None,f6f8f5,2.0
2249,41054,27849486,472,1644,EBCDIC_DIGITS,800001800001c0000200000810000000,f6f8f5f6f8f6f1f4f1f2f0f1f4f8f0f0f4f9f7f8f2f0f1...,True,685,None,f6f8f5,2.0
2250,41055,27849962,472,1644,EBCDIC_DIGITS,800001800001c0000200000810000000,f6f8f5f6f8f6f1f4f1f2f0f1f4f8f0f0f4f9f7f8f2f0f1...,True,685,None,f6f8f5,2.0
2251,41056,27850438,104,1644,EBCDIC_DIGITS,80000100000100000200000000000000,f6f9f5f0f7f0f0f1f0f5f0f2f5f0f0f1f2f6f0f1f1f3f0...,True,695,TRAILER,f6f9f5,2.0

In [26]:
df[df["function_role"] == "HEADER"]

,msg_no,offset,msg_len,mti,enc,bitmap_hex,body_hex,parse_ok,function_code,function_role,de24_raw_hex,block
0,31627,21899743,74,1644,EBCDIC_DIGITS,80000100000100000200000000000000,f6f9f7f0f4f0f0f1f0f5f0f2f5f0f0f1f2f6f0f1f1f3f0...,True,697,HEADER,f6f9f7,2.0

In [27]:
df[df["function_role"] == "TRAILER"]

,msg_no,offset,msg_len,mti,enc,bitmap_hex,body_hex,parse_ok,function_code,function_role,de24_raw_hex,block
2251,41056,27850438,104,1644,EBCDIC_DIGITS,80000100000100000200000000000000,f6f9f5f0f7f0f0f1f0f5f0f2f5f0f0f1f2f6f0f1f1f3f0...,True,695,TRAILER,f6f9f5,2.0